# Generated by Django 2.2.5 on 2019-09-17 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190917_1401'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='registerModel',
        ),
    ]
