# Generated by Django 2.2.5 on 2019-09-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190917_1419'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registerModel',
            new_name='User',
        ),
        migrations.AddField(
            model_name='anotation',
            name='isfavorite',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
    ]
